import React, { createContext, useContext, useState, useCallback } from 'react';

// ─── Translation Dictionaries ──────────────────────────────────────────────
const translations = {
    en: {
        // ── Sidebar groups ──────────────────────
        'Overview': 'Overview',
        'Front Desk': 'Front Desk',
        'Kitchen & Dining': 'Kitchen & Dining',
        'Accounts': 'Accounts',
        'Reports': 'Reports',
        'Inventory': 'Inventory',
        'Human Resources': 'Human Resources',
        'System Admin': 'System Admin',
        'Integrations': 'Integrations',

        // ── Sidebar items ───────────────────────
        'Dashboard': 'Dashboard',
        'Maintenance': 'Maintenance',
        'Issue Types': 'Issue Types',
        'Reservations': 'Reservations',
        'Check-in': 'Check-in',
        'Check-out': 'Check-out',
        'Guests': 'Guests',
        'Rooms': 'Rooms',
        'Venues': 'Venues',
        'Venue Bookings': 'Venue Bookings',
        'Housekeeping': 'Housekeeping',
        'Restaurant POS': 'Restaurant POS',
        'Quick POS': 'Quick POS',
        'Kitchen Orders': 'Kitchen Orders',
        'Menu Items': 'Menu Items',
        'Menu Categories': 'Menu Categories',
        'Tables': 'Tables',
        'Folio & Billing': 'Folio & Billing',
        'Charge Types': 'Charge Types',
        'Payment Methods': 'Payment Methods',
        'Expenses': 'Expenses',
        'Cash Movements': 'Cash Movements',
        'Petty Cash': 'Petty Cash',
        'Debtor Alerts': 'Debtor Alerts',
        'Operational Reports': 'Operational Reports',
        'Financial Audit': 'Financial Audit',
        'Stock Management': 'Stock Management',
        'Stock Categories': 'Stock Categories',
        'Inventory Units': 'Inventory Units',
        'Suppliers': 'Suppliers',
        'Purchase Orders': 'Purchase Orders',
        'Attendance': 'Attendance',
        'Leave Requests': 'Leave Requests',
        'User Management': 'User Management',
        'Employees': 'Employees',
        'Departments': 'Departments',
        'Room Types': 'Room Types',
        'Leave Types': 'Leave Types',
        'Settings': 'Settings',
        'Booking.com': 'Booking.com',
        'Logout': 'Logout',

        // ── Role labels ─────────────────────────
        'Hotel Admin': 'Hotel Admin',
        'Manager': 'Manager',
        'Receptionist': 'Receptionist',
        'Housekeeping Staff': 'Housekeeping Staff',
        'Accountant': 'Accountant',
        'Chef': 'Chef',
        'Waiter': 'Waiter',
        'Cashier': 'Cashier',
        'Store Keeper': 'Store Keeper',
        'Maintenance Staff': 'Maintenance Staff',
        'Staff': 'Staff',

        // ── Dashboard ───────────────────────────
        'Prioritize Housekeeping': 'Prioritize Housekeeping',
        'There are rooms awaiting cleaning for new arrivals.': 'There are rooms awaiting cleaning for new arrivals.',
        'Assign Tasks': 'Assign Tasks',
        'Expected Arrivals': 'Expected Arrivals',
        'Check-in desk': 'Check-in desk',
        'Expected Departures': 'Expected Departures',
        'Check-out desk': 'Check-out desk',
        'Clean & Ready': 'Clean & Ready',
        'Dirty / Pending': 'Dirty / Pending',
        'Out of Order': 'Out of Order',
        'Recent Arrivals': 'Recent Arrivals',
        'Latest 5': 'Latest 5',
        'No arrivals recorded for today.': 'No arrivals recorded for today.',
        'Operational Health': 'Operational Health',
        'Global Occupancy': 'Global Occupancy',
        'In-House': 'In-House',
        'Available': 'Available',
        'Available by Type': 'Available by Type',
        'Occupancy Target': 'Occupancy Target',
        '85% Goal': '85% Goal',
        'Growth Status': 'Growth Status',
        'Current': 'Current',
        'Direct Guest': 'Direct Guest',
        'Room': 'Room',
        'TBD': 'TBD',

        // ── Common UI ───────────────────────────
        'Search': 'Search',
        'Filter': 'Filter',
        'Actions': 'Actions',
        'Edit': 'Edit',
        'Delete': 'Delete',
        'Cancel': 'Cancel',
        'Save': 'Save',
        'Save Changes': 'Save Changes',
        'Discard': 'Discard',
        'Confirm': 'Confirm',
        'Add': 'Add',
        'Create': 'Create',
        'Update': 'Update',
        'Submit': 'Submit',
        'Close': 'Close',
        'Loading...': 'Loading...',
        'No data found': 'No data found',
        'Name': 'Name',
        'Description': 'Description',
        'Status': 'Status',
        'Date': 'Date',
        'Notes': 'Notes',
        'Amount': 'Amount',
        'Total': 'Total',
        'Type': 'Type',
        'Floor': 'Floor',
        'Reference': 'Reference',
        'Night(s)': 'Night(s)',
        'Active': 'Active',
        'Inactive': 'Inactive',
        'Void': 'Void',
        'All Status': 'All Status',
        'Pending': 'Pending',
        'Completed': 'Completed',
        'Cancelled': 'Cancelled',
        'Configure Types': 'Configure Types',
        'Refresh': 'Refresh',

        // ── Reservations page ──────────────────
        'New Reservation': '+ New Reservation',
        'Total Bookings': 'Total Bookings',
        'Pending Arrivals': 'Pending Arrivals',
        'In-House Now': 'In-House Now',
        'Search by guest name...': 'Search by guest name...',
        'Guest': 'Guest',
        'Type & Info': 'Type & Info',
        'Schedule': 'Schedule',
        'No reservations found': 'No reservations found',
        'No email provided': 'No email provided',
        'Manage': 'Manage',
        'Modify Reservation': 'Modify Reservation',
        'Create New Booking': 'Create New Booking',
        'Select Guest': 'Select Guest',
        '+ New Guest': '+ New Guest',
        '-- Search for a Guest --': '-- Search for a Guest --',
        'Booking Type': 'Booking Type',
        'Room Only': 'Room Only',
        'Table Only': 'Table Only',
        'Both': 'Both',
        'Stay Configuration': 'Stay Configuration',
        'Room Category': 'Room Category',
        '-- Select Type --': '-- Select Type --',
        'Occupancy (Adults / Kids)': 'Occupancy (Adults / Kids)',
        'Dining Reservation': 'Dining Reservation',
        'Table Assignment': 'Table Assignment',
        '-- Choose Table --': '-- Choose Table --',
        'Dining Time': 'Dining Time',
        'Table Pax': 'Table Pax',
        'Notes & Requests': 'Notes & Requests',
        'Enter any guest requests or preferences...': 'Enter any guest requests or preferences...',
        'Update Booking': 'Update Booking',
        'Confirm Reservation': 'Confirm Reservation',
        'Quick Register Guest': 'Quick Register Guest',
        'Record Reservation Payment': 'Record Reservation Payment',
        'Guest Portfolio': 'Guest Portfolio',
        'Outstanding Balance': 'Outstanding Balance',
        'Amount to Pay ($)': 'Amount to Pay ($)',
        'Payment Method': 'Payment Method',
        'Reference Code': 'Reference Code',
        'Receipt / TXN ID': 'Receipt / TXN ID',
        'Internal Notes': 'Internal Notes',
        'Optional comments...': 'Optional comments...',
        'Confirm Payment': 'Confirm Payment',
        'Manage Booking': 'Manage Booking',
        'Check-In Guest': 'Check-In Guest',
        'Receive Payment': 'Receive Payment',
        'Add to Folio': 'Add to Folio',
        'Edit Details': 'Edit Details',
        'Modify Booking': 'Modify Booking',
        'Mark No-Show': 'Mark No-Show',
        'Release Room/Table': 'Release Room/Table',
        'Cancel Booking': 'Cancel Booking',
        'Void Reservation': 'Void Reservation',
        'Try adjusting your filters or search query.': 'Try adjusting your filters or search query.',

        // ── Rooms page ─────────────────────────
        'Search Room Number or Type...': 'Search Room Number or Type...',
        'Add New Room': 'Add New Room',
        'Loading rooms...': 'Loading rooms...',
        'Room Number': 'Room Number',
        'Needs Cleaning': 'Needs Cleaning',
        'Clean': 'Clean',
        'No rooms match your search.': 'No rooms match your search.',
        'No rooms found.': 'No rooms found.',
        'Edit Room': 'Edit Room',
        'Add Room Category': 'Add Room Category',
        'Category Name': 'Category Name',
        'Base Price ($)': 'Base Price ($)',
        'Create Category': 'Create Category',
        'Save Room': 'Save Room',

        // ── Guests page ─────────────────────────
        'Search guests by name, phone, email or ID...': 'Search guests by name, phone, email or ID...',
        'Register Guest': 'Register Guest',
        'Loading guests...': 'Loading guests...',
        'Contact': 'Contact',
        'ID Info': 'ID Info',
        'Nationality': 'Nationality',
        'Check In': 'Check In',
        'Guest Profile': 'Guest Profile',
        'Register New Guest': 'Register New Guest',
        'Profile Details': 'Profile Details',
        'Stay History': 'Stay History',
        'Loading history...': 'Loading history...',
        'Dates': 'Dates',
        'Duration': 'Duration',
        'No past stays recorded for this guest.': 'No past stays recorded for this guest.',

        // ── Housekeeping page ───────────────────
        'Housekeeping Board': 'Housekeeping Board',
        'Manage room turnovers and cleaning cycles.': 'Manage room turnovers and cleaning cycles.',
        'Start Cleaning': 'Start Cleaning',
        'Mark as Inspected': 'Mark as Inspected',
        'Ready for Guests': 'Ready for Guests',
        'All Rooms are Clean!': 'All Rooms are Clean!',
        'There are currently no rooms marked as Dirty or Cleaning in the system.': 'There are currently no rooms marked as Dirty or Cleaning in the system.',

        // ── Check-in page ───────────────────────
        'Check-In': 'Check-In',
        'Guest Check-In': 'Guest Check-In',
        'Select Reservation': 'Select Reservation',
        'Assign Room': 'Assign Room',
        'Confirm Check-In': 'Confirm Check-In',
        'No reservations pending check-in.': 'No reservations pending check-in.',
        'Search reservations...': 'Search reservations...',
        'Room Assignment': 'Room Assignment',
        'Select available room': 'Select available room',
        'Proceed to Check-In': 'Proceed to Check-In',
        'Check-In Confirmed': 'Check-In Confirmed',

        // ── Check-out page ──────────────────────
        'Check-Out': 'Check-Out',
        'Guest Check-Out': 'Guest Check-Out',
        'Folio Summary': 'Folio Summary',
        'Process Check-Out': 'Process Check-Out',
        'No guests due for check-out.': 'No guests due for check-out.',
        'Settle & Check Out': 'Settle & Check Out',
        'Balance Due': 'Balance Due',
        'Settled': 'Settled',

        // ── Maintenance page ────────────────────
        'Maintenance Requests': 'Maintenance Requests',
        'New Request': 'New Request',
        'Issue Type': 'Issue Type',
        'Priority': 'Priority',
        'Reported By': 'Reported By',
        'Assigned To': 'Assigned To',
        'Report Issue': 'Report Issue',
        'Open': 'Open',
        'In Progress': 'In Progress',
        'Resolved': 'Resolved',
        'No maintenance requests found.': 'No maintenance requests found.',
        'HIGH': 'HIGH',
        'MEDIUM': 'MEDIUM',
        'LOW': 'LOW',

        // ── Folio & Billing ─────────────────────
        'Folio': 'Folio',
        'Billing': 'Billing',
        'Charge': 'Charge',
        'Payment': 'Payment',
        'Add Charge': 'Add Charge',
        'Record Payment': 'Record Payment',
        'Charges': 'Charges',
        'Payments': 'Payments',
        'Net Balance': 'Net Balance',
        'Folio #': 'Folio #',
        'No folio found.': 'No folio found.',
        'Post Charge': 'Post Charge',
        'Charge Type': 'Charge Type',

        // ── Restaurant / Kitchen ────────────────
        'New Order': 'New Order',
        'Table': 'Table',
        'Order Items': 'Order Items',
        'Subtotal': 'Subtotal',
        'Quantity': 'Quantity',
        'Place Order': 'Place Order',
        'Kitchen Queue': 'Kitchen Queue',
        'Mark Ready': 'Mark Ready',
        'Mark Served': 'Mark Served',
        'Pending Orders': 'Pending Orders',
        'No pending orders.': 'No pending orders.',

        // ── Inventory ───────────────────────────
        'Stock Level': 'Stock Level',
        'Unit': 'Unit',
        'Category': 'Category',
        'Reorder Level': 'Reorder Level',
        'Current Stock': 'Current Stock',
        'Add Stock': 'Add Stock',
        'Low Stock': 'Low Stock',
        'Supplier': 'Supplier',
        'No stock items found.': 'No stock items found.',

        // ── HR / Attendance ─────────────────────
        'Mark Attendance': 'Mark Attendance',
        'Check In Time': 'Check In Time',
        'Check Out Time': 'Check Out Time',
        'Employee': 'Employee',
        'Department': 'Department',
        'Leave Type': 'Leave Type',
        'Start Date': 'Start Date',
        'End Date': 'End Date',
        'Apply for Leave': 'Apply for Leave',
        'Approved': 'Approved',
        'Rejected': 'Rejected',

        // ── Reports ─────────────────────────────
        'Revenue': 'Revenue',
        'Daily Revenue': 'Daily Revenue',
        'Monthly Revenue': 'Monthly Revenue',
        'Occupancy Rate': 'Occupancy Rate',
        'ADR': 'ADR',
        'RevPAR': 'RevPAR',
        'Generate Report': 'Generate Report',
        'Export': 'Export',
        'Date Range': 'Date Range',
        'From': 'From',
        'To': 'To',

        // ── Settings / Users ────────────────────
        'Add User': 'Add User',
        'Role': 'Role',
        'Username': 'Username',
        'Password': 'Password',
        'Email': 'Email',
        'Phone': 'Phone',
        'Created': 'Created',
        'No users found.': 'No users found.',

        // ── Extended Folio keys ──────────────────
        'Search by Folio ID...': 'Search by Folio ID...',
        'All Folios': 'All Folios',
        'Open Folios': 'Open Folios',
        'Closed Folios': 'Closed Folios',
        'Guest / Details': 'Guest / Details',
        'Opened At': 'Opened At',
        'Total Balance': 'Total Balance',
        'Pay': 'Pay',
        'Receipts': 'Receipts',
        'Settle': 'Settle',
        'No active folios found.': 'No active folios found.',
        'Submit Charge': 'Submit Charge',
        'Unit Price ($)': 'Unit Price ($)',
        'Existing Methods': 'Existing Methods',
        'Add New Method': 'Add New Method',
        'Method Name': 'Method Name',
        'Add Method': 'Add Method',
        'No payment methods defined yet.': 'No payment methods defined yet.',
        'No receipts found for this folio.': 'No receipts found for this folio.',
        'Print Official Receipt': 'Print Official Receipt',
        'Amount Paid:': 'Amount Paid:',
        'Total Value': 'Total Value',

        // ── Extended Users keys ──────────────────
        'Add New User': 'Add New User',
        'User Profile': 'User Profile',
        'System Role': 'System Role',
        'Contact Details': 'Contact Details',
        'Full Name': 'Full Name',
        'Email Address': 'Email Address',
        'Phone Number': 'Phone Number',
        'New Password (Optional)': 'New Password (Optional)',
        'Initial Password': 'Initial Password',
        'Account Active & Enabled': 'Account Active & Enabled',
        'Provision User': 'Provision User',
        'Update Profile': 'Update Profile',
        'Configure': 'Configure',
        'Retract Access': 'Retract Access',
        'Authenticated': 'Authenticated',
        'Disabled': 'Disabled',

        // ── Extended Employees keys ──────────────
        'Add Employee': 'Add Employee',
        'Manage Departments': 'Manage Departments',
        'Register New Staff Member': 'Register New Staff Member',
        'Edit Employee Details': 'Edit Employee Details',
        'Designation': 'Designation',
        'Basic Salary ($)': 'Basic Salary ($)',
        'Date of Joining': 'Date of Joining',
        'Languages Spoken': 'Languages Spoken',
        'ID Type': 'ID Type',
        'Passport / ID Number': 'Passport / ID Number',
        'KRA PIN (Optional)': 'KRA PIN (Optional)',
        'Department Name': 'Department Name',
        'Create Department': 'Create Department',
        'No staff members found.': 'No staff members found.',
        'Salary & Joining': 'Salary & Joining',
        'Identity': 'Identity',
        'Languages': 'Languages',

        // ── Extended Room Types keys ─────────────
        'Add Room Type': 'Add Room Type',
        'Edit Room Type': 'Edit Room Type',
        'Register New Type': 'Register New Type',
        'Room Category Name': 'Room Category Name',
        'Max Occupancy': 'Max Occupancy',
        'Bed Configuration': 'Bed Configuration',
        'Room Rate ($ per Night)': 'Room Rate ($ per Night)',
        'Save Settings': 'Save Settings',
        'No room types defined yet.': 'No room types defined yet.',
        'Setup': 'Setup',
        'Rate': 'Rate',

        // ── POS keys ────────────────────────────
        'All Items': 'All Items',
        'Current Ticket': 'Current Ticket',
        'Ticket is empty': 'Ticket is empty',
        'Immediate Payment (Direct)': 'Immediate Payment (Direct)',
        'Charge to Room': 'Charge to Room',
        'Direct Payment': 'Direct Payment',
        'Room Tab': 'Room Tab',
        'Guest Name (Optional)': 'Guest Name (Optional)',
        'Post Charge to Folio': 'Post Charge to Folio',
        'Processing...': 'Processing...',

        // ── Shared labels ────────────────────────
        'Adults': 'Adults',
        'Children': 'Children',
        'Not in the list?': 'Not in the list?',
        'REGISTER NEW GUEST': 'REGISTER NEW GUEST',
        'City or Country': 'City or Country',
        'Target Destination': 'Target Destination',
        'Arriving From': 'Arriving From',
        'Next Destination': 'Next Destination',
        'Arrival Flight #': 'Arrival Flight #',
        'Departure Flight #': 'Departure Flight #',
        'Stay Notes': 'Stay Notes',
        'Special requests, billing instructions, etc.': 'Special requests, billing instructions, etc.',
        'Expected Checkout Date': 'Expected Checkout Date',
        'The total room charge will be calculated and posted to the folio automatically based on this date.': 'The total room charge will be calculated and posted to the folio automatically based on this date.',
        'Available Rooms': 'Available Rooms',
        'No available rooms match this category.': 'No available rooms match this category.',
        '-- Select Room Number --': '-- Select Room Number --',
        '-- Choose Room --': '-- Choose Room --',
        'Record Arrival Payment': 'Record Arrival Payment',
        'Current Balance': 'Current Balance',
        'Overdue': 'Overdue',
        'Due Today': 'Due Today',
        'Print Report': 'Print Report',
        'Download CSV': 'Download CSV',
        'Management Reports': 'Management Reports',
        'Assign to Me': 'Assign to Me',
        'Resolve': 'Resolve',
        'Reported by': 'Reported by',
        'Issue Details': 'Issue Details',
        'Location / ID': 'Location / ID',
        'Folio ID': 'Folio ID',

        // Additional Reports & Finance Keys
        'Gross': 'Gross',
        'No guests found.': 'No guests found.',
        'Actual payments received': 'Actual payments received',
        'Operational expenditures': 'Operational expenditures',
        'Accounts Payable': 'Accounts Payable',
        'Inventory Assets': 'Inventory Assets',
        '✓ Paid': '✓ Paid',
        'Share (%)': 'Share (%)',
        'General Ledger': 'General Ledger',
        'Total Expenses': 'Total Expenses',
        'Running Balance': 'Running Balance',
        'All Maintenance Tickets': 'All Maintenance Tickets',
        'available': 'available',
        'Guest Report': 'Guest Report',
        'Guests checking in today': 'Guests checking in today',
        'Collections - OpEx': 'Collections - OpEx',
        'Treasury Audit': 'Treasury Audit',
        'Repairs & Upkeep': 'Repairs & Upkeep',
        'All Reservations': 'All Reservations',
        'F&B / POS Report': 'F&B / POS Report',
        'Count': 'Count',
        'All Registered Guests': 'All Registered Guests',
        'Arrivals Today': 'Arrivals Today',
        'New Arrivals Today': 'New Arrivals Today',
        'Checked In': 'Checked In',
        'Date In': 'Date In',
        'Share': 'Share',
        'Net Collections': 'Net Collections',
        'Payroll Liability': 'Payroll Liability',
        'Total Reservations': 'Total Reservations',
        'Daily cash spend': 'Daily cash spend',
        'Revenue Report': 'Revenue Report',
        'All Venue Bookings': 'All Venue Bookings',
        'Total Items': 'Total Items',
        'Urgent / High': 'Urgent / High',
        'Venue': 'Venue',
        'Item Name': 'Item Name',
        'Daily Cash Spend': 'Daily Cash Spend',
        'Client': 'Client',
        'Debit / Credit': 'Debit / Credit',
        'Guests with Active Stays': 'Guests with Active Stays',
        'Issue': 'Issue',
        'Inventory Report': 'Inventory Report',
        'Venue Bookings Report': 'Venue Bookings Report',
        'Active Collections': 'Active Collections',
        'No venue bookings found.': 'No venue bookings found.',
        'Dining Orders': 'Dining Orders',
        'Revenue by Charge Type': 'Revenue by Charge Type',
        'Supply Spend': 'Supply Spend',
        'All Inventory Items': 'All Inventory Items',
        'Financial Reports': 'Financial Reports',
        'No reservations found.': 'No reservations found.',
        'Account': 'Account',
        'By Department': 'By Department',
        'Owed to Suppliers': 'Owed to Suppliers',
        'No department data.': 'No department data.',
        'Amount ($)': 'Amount ($)',
        'Reservations Report': 'Reservations Report',
        'Dining Sessions': 'Dining Sessions',
        'Maintenance Report': 'Maintenance Report',
        'Guests checking out today': 'Guests checking out today',
        'Net Revenue': 'Net Revenue',
        'Open Sessions': 'Open Sessions',
        'All-time Folio Value': 'All-time Folio Value',
        'Cash Collected': 'Cash Collected',
        'Out of Stock': 'Out of Stock',
        'Booked': 'Booked',
        'Event': 'Event',
        'Revenue audit and cash collection tracking': 'Revenue audit and cash collection tracking',
        'Total Employees': 'Total Employees',
        'Confirmed': 'Confirmed',
        'Billed Revenue': 'Billed Revenue',
        'Accounts Receivable': 'Accounts Receivable',
        'Staff Salaries': 'Staff Salaries',
        'Debtor Tracking': 'Debtor Tracking',
        'Total invoices generated': 'Total invoices generated',
        'Timestamp': 'Timestamp',
        'Session': 'Session',
        'Total ($)': 'Total ($)',
        'No dining orders found.': 'No dining orders found.',
        'ID Number': 'ID Number',
        'Employee Report': 'Employee Report',
        'Total Orders': 'Total Orders',
        'Deposit': 'Deposit',
        'Well Stocked': 'Well Stocked',
        'Stock Value': 'Stock Value',
        'Pending Folios': 'Pending Folios',
        'occupied': 'occupied',
        'Items with 0 quantity': 'Items with 0 quantity',
        'Due from Guests': 'Due from Guests',
        'No employees found.': 'No employees found.',
        'Stock Status': 'Stock Status',
        'Net Cash from Operations': 'Net Cash from Operations',
        'Departures Today': 'Departures Today',
        'Running Balance History': 'Running Balance History',
        'Liquidity Summary': 'Liquidity Summary',
        'Total POS Revenue': 'Total POS Revenue',
        'Items': 'Items',
        'Procurement': 'Procurement',
        'Total Guests': 'Total Guests',
        'Unrealized Revenue': 'Unrealized Revenue',
        'No maintenance tickets found.': 'No maintenance tickets found.',
        'Total Tickets': 'Total Tickets',
        'Employee Directory': 'Employee Directory',
        '✗ Unpaid': '✗ Unpaid',

        'Receptionist Performance Report': 'Receptionist Performance Report',
        'Financial collections and client volume by user': 'Financial collections and client volume by user',
        'Clients Served': 'Clients Served',
        'Period Revenue': 'Period Revenue',
        'Refresh Reports': 'Refresh Reports',
        'Calculating...': 'Calculating...',
        'Performance and operational snapshot': 'Performance and operational snapshot',


        // ── Admin, HR & Inventory Extended ────
        'Loading user accounts...': 'Loading user accounts...',
        'No Email': 'No Email',
        'No Phone': 'No Phone',
        'Edit Profile': 'Edit Profile',
        'Logo': 'Logo',
        'Upload New Logo': 'Upload New Logo',
        'General Details': 'General Details',
        'Legal & Registration': 'Legal & Registration',
        'Registered': 'Registered',
        'Not Registered': 'Not Registered',
        'Operations': 'Operations',
        'Taxes & Charges config': 'Taxes & Charges config',
        'Update Property Profile': 'Update Property Profile',
        'Entity Categories': 'Entity Categories',
        'Add New': 'Add New',
        'Syncing entries...': 'Syncing entries...',
        'N/A': 'N/A',
        'No results found for this category': 'No results found for this category',
        'Click here to add your first record': 'Click here to add your first record',
        'Edit User Profile': 'Edit User Profile',
        'Create New User Account': 'Create New User Account',
        'Account Password': 'Account Password',
        'Account is Active (Allow login and system access)': 'Account is Active (Allow login and system access)',
        'Save Updates': 'Save Updates',
        'Create Account': 'Create Account',
        'Edit Definition': 'Edit Definition',
        'Add New Entry': 'Add New Entry',
        'Update Entry': 'Update Entry',
        'Create Entry': 'Create Entry',
        'Search departments...': 'Search departments...',
        'Add Department': 'Add Department',
        'No departments match your search.': 'No departments match your search.',
        'No departments found.': 'No departments found.',
        'Edit Department': 'Edit Department',
        'Add New Department': 'Add New Department',
        'e.g. Front Office': 'e.g. Front Office',
        'Update Department': 'Update Department',
        'Search leave types...': 'Search leave types...',
        'Add Leave Type': 'Add Leave Type',
        'Syncing HR records...': 'Syncing HR records...',
        'No leave policies match your search.': 'No leave policies match your search.',
        'No leave types registered.': 'No leave types registered.',
        'Edit Leave Type': 'Edit Leave Type',
        'Create HR Policy': 'Create HR Policy',
        'Policy Name': 'Policy Name',
        'e.g. Annual Leave, Sick Leave': 'e.g. Annual Leave, Sick Leave',
        'Save Policy': 'Save Policy',
        'Manage and track employee absence requests.': 'Manage and track employee absence requests.',
        'Submit Request': 'Submit Request',
        'Leave History': 'Leave History',
        'Real-time Updates': 'Real-time Updates',
        'Total duration:': 'Total duration:',
        'days': 'days',
        'General Leave': 'General Leave',
        'Approve': 'Approve',
        'Reject': 'Reject',
        'Processed': 'Processed',
        'No leave requests found.': 'No leave requests found.',
        'Leave Policy': 'Leave Policy',
        'Carry Forward': 'Carry Forward',
        'Days': 'Days',
        'Notice Period': 'Notice Period',
        'Hours': 'Hours',
        'Pending Approval': 'Pending Approval',
        'New Leave Request': 'New Leave Request',
        'Leave Category': 'Leave Category',
        'Reason for Absence': 'Reason for Absence',
        'Briefly describe the reason for your leave...': 'Briefly describe the reason for your leave...',
        'Daily Attendance': 'Daily Attendance',
        'Capture your work hours and stay update with your schedule.': 'Capture your work hours and stay update with your schedule.',
        'Clock Out': 'Clock Out',
        'Clock In Now': 'Clock In Now',
        'Attendance Logs': 'Attendance Logs',
        'Search by name or date...': 'Search by name or date...',
        'hrs': 'hrs',
        'No attendance records found.': 'No attendance records found.',
        'Search items by name or category...': 'Search items by name or category...',
        'Manage Categories': 'Manage Categories',
        'Manage Units': 'Manage Units',
        'Add Item': 'Add Item',
        'Loading inventory...': 'Loading inventory...',
        'Min': 'Min',
        'No inventory items found matching': 'No inventory items found matching',
        'Edit Inventory Item': 'Edit Inventory Item',
        'Add New Inventory Item': 'Add New Inventory Item',
        'e.g. Toilet Paper': 'e.g. Toilet Paper',
        'Add New Unit': 'Add New Unit',
        'Add any specific storage instructions or details...': 'Add any specific storage instructions or details...',
        'Update Inventory': 'Update Inventory',
        'Quick Add Category': 'Quick Add Category',
        'e.g. Toiletries': 'e.g. Toiletries',
        'Adding...': 'Adding...',
        'Add Category': 'Add Category',
        'Add Inventory Unit': 'Add Inventory Unit',
        'e.g. Kg, Pcs, Box': 'e.g. Kg, Pcs, Box',
        'e.g. Kilograms': 'e.g. Kilograms',
        'Create Unit': 'Create Unit',
        'Loading categories...': 'Loading categories...',
        'No inventory categories found.': 'No inventory categories found.',
        'Edit Category': 'Edit Category',
        'Add New Category': 'Add New Category',
        'e.g. Toiletries, Perishables': 'e.g. Toiletries, Perishables',
        'Save Category': 'Save Category',
    },
    zh: {
        // ── Sidebar groups ──────────────────────
        'Overview': '概览',
        'Front Desk': '前台',
        'Kitchen & Dining': '厨房与餐饮',
        'Accounts': '财务账目',
        'Reports': '报告',
        'Inventory': '库存',
        'Human Resources': '人力资源',
        'System Admin': '系统管理',
        'Integrations': '第三方集成',

        // ── Sidebar items ───────────────────────
        'Dashboard': '仪表板',
        'Maintenance': '维修管理',
        'Issue Types': '问题类型',
        'Reservations': '预订',
        'Check-in': '入住',
        'Check-out': '退房',
        'Guests': '宾客',
        'Rooms': '房间',
        'Venues': '场地',
        'Venue Bookings': '场地预订',
        'Housekeeping': '客房清洁',
        'Restaurant POS': '餐厅收银',
        'Quick POS': '快捷收银',
        'Kitchen Orders': '厨房订单',
        'Menu Items': '菜单项目',
        'Menu Categories': '菜单分类',
        'Tables': '餐桌',
        'Folio & Billing': '账单结算',
        'Charge Types': '收费类型',
        'Payment Methods': '支付方式',
        'Expenses': '支出',
        'Cash Movements': '现金流动',
        'Petty Cash': '零用现金',
        'Debtor Alerts': '欠款提醒',
        'Operational Reports': '运营报告',
        'Financial Audit': '财务审计',
        'Stock Management': '库存管理',
        'Stock Categories': '库存分类',
        'Inventory Units': '库存单位',
        'Suppliers': '供应商',
        'Purchase Orders': '采购订单',
        'Attendance': '考勤',
        'Leave Requests': '请假申请',
        'User Management': '用户管理',
        'Employees': '员工',
        'Departments': '部门',
        'Room Types': '房型',
        'Leave Types': '假期类型',
        'Settings': '系统设置',
        'Booking.com': 'Booking.com',
        'Logout': '退出登录',

        // ── Role labels ─────────────────────────
        'Hotel Admin': '酒店管理员',
        'Manager': '经理',
        'Receptionist': '前台接待',
        'Housekeeping Staff': '客房服务员',
        'Accountant': '会计',
        'Chef': '厨师',
        'Waiter': '服务员',
        'Cashier': '收银员',
        'Store Keeper': '仓库管理员',
        'Maintenance Staff': '维修人员',
        'Staff': '员工',

        // ── Dashboard ───────────────────────────
        'Prioritize Housekeeping': '优先客房清洁',
        'There are rooms awaiting cleaning for new arrivals.': '有房间尚待清洁，以迎接新抵达的宾客。',
        'Assign Tasks': '分配任务',
        'Expected Arrivals': '预计入住',
        'Check-in desk': '入住前台',
        'Expected Departures': '预计退房',
        'Check-out desk': '退房前台',
        'Clean & Ready': '干净可用',
        'Dirty / Pending': '待清洁',
        'Out of Order': '停用维修',
        'Recent Arrivals': '最新入住',
        'Latest 5': '最近5条',
        'No arrivals recorded for today.': '今日暂无入住记录。',
        'Operational Health': '运营状况',
        'Global Occupancy': '整体入住率',
        'In-House': '在住',
        'Available': '可用',
        'Available by Type': '按类型可用数',
        'Occupancy Target': '入住率目标',
        '85% Goal': '目标85%',
        'Growth Status': '增长状态',
        'Current': '当前',
        'Direct Guest': '直接入住',
        'Room': '房间',
        'TBD': '待定',

        // ── Common UI ───────────────────────────
        'Search': '搜索',
        'Filter': '筛选',
        'Actions': '操作',
        'Edit': '编辑',
        'Delete': '删除',
        'Cancel': '取消',
        'Save': '保存',
        'Save Changes': '保存更改',
        'Discard': '放弃',
        'Confirm': '确认',
        'Add': '添加',
        'Create': '创建',
        'Update': '更新',
        'Submit': '提交',
        'Close': '关闭',
        'Loading...': '加载中...',
        'No data found': '未找到数据',
        'Name': '名称',
        'Description': '描述',
        'Status': '状态',
        'Date': '日期',
        'Notes': '备注',
        'Amount': '金额',
        'Total': '合计',
        'Type': '类型',
        'Floor': '楼层',
        'Reference': '参考编号',
        'Night(s)': '晚',
        'Active': '活跃',
        'Inactive': '停用',
        'Void': '作废',
        'All Status': '全部状态',
        'Pending': '待确认',
        'Completed': '已完成',
        'Cancelled': '已取消',
        'Configure Types': '配置类型',
        'Refresh': '刷新',

        // ── Reservations page ──────────────────
        'New Reservation': '+ 新建预订',
        'Total Bookings': '预订总数',
        'Pending Arrivals': '待入住',
        'In-House Now': '当前在住',
        'Search by guest name...': '按宾客姓名搜索...',
        'Guest': '宾客',
        'Type & Info': '类型与信息',
        'Schedule': '日程',
        'No reservations found': '未找到预订',
        'No email provided': '无邮箱',
        'Manage': '管理',
        'Modify Reservation': '修改预订',
        'Create New Booking': '新建预订',
        'Select Guest': '选择宾客',
        '+ New Guest': '+ 新建宾客',
        '-- Search for a Guest --': '-- 搜索宾客 --',
        'Booking Type': '预订类型',
        'Room Only': '仅房间',
        'Table Only': '仅餐桌',
        'Both': '两者均预订',
        'Stay Configuration': '住宿设置',
        'Room Category': '房型',
        '-- Select Type --': '-- 选择类型 --',
        'Occupancy (Adults / Kids)': '入住人数（大人 / 小孩）',
        'Dining Reservation': '餐饮预订',
        'Table Assignment': '分配餐桌',
        '-- Choose Table --': '-- 选择餐桌 --',
        'Dining Time': '用餐时间',
        'Table Pax': '用餐人数',
        'Notes & Requests': '备注与特殊要求',
        'Enter any guest requests or preferences...': '输入宾客要求或偏好...',
        'Update Booking': '更新预订',
        'Confirm Reservation': '确认预订',
        'Quick Register Guest': '快速注册宾客',
        'Record Reservation Payment': '记录预订付款',
        'Guest Portfolio': '宾客档案',
        'Outstanding Balance': '未结余额',
        'Amount to Pay ($)': '付款金额 ($)',
        'Payment Method': '支付方式',
        'Reference Code': '参考编号',
        'Receipt / TXN ID': '收据 / 交易编号',
        'Internal Notes': '内部备注',
        'Optional comments...': '选填备注...',
        'Confirm Payment': '确认付款',
        'Manage Booking': '管理预订',
        'Check-In Guest': '办理入住',
        'Receive Payment': '收款',
        'Add to Folio': '记入账单',
        'Edit Details': '编辑详情',
        'Modify Booking': '修改预订',
        'Mark No-Show': '标记未出现',
        'Release Room/Table': '释放房间/餐桌',
        'Cancel Booking': '取消预订',
        'Void Reservation': '作废预订',
        'Try adjusting your filters or search query.': '请尝试调整筛选条件或搜索内容。',

        // ── Rooms page ─────────────────────────
        'Search Room Number or Type...': '搜索房号或房型...',
        'Add New Room': '添加新房间',
        'Loading rooms...': '正在加载房间...',
        'Room Number': '房号',
        'Needs Cleaning': '需要清洁',
        'Clean': '已清洁',
        'No rooms match your search.': '没有符合搜索条件的房间。',
        'No rooms found.': '未找到房间。',
        'Edit Room': '编辑房间',
        'Add Room Category': '添加房型',
        'Category Name': '类别名称',
        'Base Price ($)': '基础价格 ($)',
        'Create Category': '创建类别',
        'Save Room': '保存房间',

        // ── Guests page ─────────────────────────
        'Search guests by name, phone, email or ID...': '按姓名、电话、邮箱或证件号搜索宾客...',
        'Register Guest': '注册宾客',
        'Loading guests...': '正在加载宾客...',
        'Contact': '联系方式',
        'ID Info': '证件信息',
        'Nationality': '国籍',
        'Check In': '办理入住',
        'Guest Profile': '宾客档案',
        'Register New Guest': '注册新宾客',
        'Profile Details': '档案详情',
        'Stay History': '住宿历史',
        'Loading history...': '正在加载历史...',
        'Dates': '日期',
        'Duration': '时长',
        'No past stays recorded for this guest.': '该宾客暂无历史住宿记录。',

        // ── Housekeeping page ───────────────────
        'Housekeeping Board': '客房清洁看板',
        'Manage room turnovers and cleaning cycles.': '管理房间周转和清洁周期。',
        'Start Cleaning': '开始清洁',
        'Mark as Inspected': '标记为已检查',
        'Ready for Guests': '已准备好迎客',
        'All Rooms are Clean!': '所有房间均已清洁！',
        'There are currently no rooms marked as Dirty or Cleaning in the system.': '系统中目前没有标记为脏或正在清洁的房间。',

        // ── Check-in page ───────────────────────
        'Check-In': '办理入住',
        'Guest Check-In': '宾客入住',
        'Select Reservation': '选择预订',
        'Assign Room': '分配房间',
        'Confirm Check-In': '确认入住',
        'No reservations pending check-in.': '暂无待入住预订。',
        'Search reservations...': '搜索预订...',
        'Room Assignment': '分配房间',
        'Select available room': '选择可用房间',
        'Proceed to Check-In': '继续办理入住',
        'Check-In Confirmed': '入住已确认',

        // ── Check-out page ──────────────────────
        'Check-Out': '退房',
        'Guest Check-Out': '宾客退房',
        'Folio Summary': '账单摘要',
        'Process Check-Out': '处理退房',
        'No guests due for check-out.': '暂无待退房宾客。',
        'Settle & Check Out': '结算并退房',
        'Balance Due': '应付余额',
        'Settled': '已结清',

        // ── Maintenance page ────────────────────
        'Maintenance Requests': '维修申请',
        'New Request': '新建申请',
        'Issue Type': '问题类型',
        'Priority': '优先级',
        'Reported By': '上报人',
        'Assigned To': '负责人',
        'Report Issue': '上报问题',
        'Open': '未处理',
        'In Progress': '处理中',
        'Resolved': '已解决',
        'No maintenance requests found.': '未找到维修申请。',
        'HIGH': '高',
        'MEDIUM': '中',
        'LOW': '低',

        // ── Folio & Billing ─────────────────────
        'Folio': '账单',
        'Billing': '结账',
        'Charge': '收费',
        'Payment': '付款',
        'Add Charge': '添加收费',
        'Record Payment': '记录付款',
        'Charges': '收费记录',
        'Payments': '付款记录',
        'Net Balance': '净余额',
        'Folio #': '账单编号',
        'No folio found.': '未找到账单。',
        'Post Charge': '记入费用',
        'Charge Type': '收费类型',

        // ── Restaurant / Kitchen ────────────────
        'New Order': '新建订单',
        'Table': '餐桌',
        'Order Items': '点餐项目',
        'Subtotal': '小计',
        'Quantity': '数量',
        'Place Order': '提交订单',
        'Kitchen Queue': '厨房队列',
        'Mark Ready': '标记就绪',
        'Mark Served': '标记已上菜',
        'Pending Orders': '待处理订单',
        'No pending orders.': '暂无待处理订单。',

        // ── Inventory ───────────────────────────
        'Stock Level': '库存水平',
        'Unit': '单位',
        'Category': '类别',
        'Reorder Level': '补货阈值',
        'Current Stock': '当前库存',
        'Add Stock': '添加库存',
        'Low Stock': '库存不足',
        'Supplier': '供应商',
        'No stock items found.': '未找到库存项目。',

        // ── HR / Attendance ─────────────────────
        'Mark Attendance': '标记考勤',
        'Check In Time': '签到时间',
        'Check Out Time': '签退时间',
        'Employee': '员工',
        'Department': '部门',
        'Leave Type': '假期类型',
        'Start Date': '开始日期',
        'End Date': '结束日期',
        'Apply for Leave': '申请休假',
        'Approved': '已批准',
        'Rejected': '已拒绝',

        // ── Reports ─────────────────────────────
        'Revenue': '营收',
        'Daily Revenue': '日营收',
        'Monthly Revenue': '月营收',
        'Occupancy Rate': '入住率',
        'ADR': '平均房价',
        'RevPAR': '每间可用客房收益',
        'Generate Report': '生成报告',
        'Export': '导出',
        'Date Range': '日期范围',
        'From': '从',
        'To': '至',

        // ── Settings / Users ────────────────────
        'Add User': '添加用户',
        'Role': '角色',
        'Username': '用户名',
        'Password': '密码',
        'Email': '邮箱',
        'Phone': '电话',
        'Created': '创建日期',
        'No users found.': '未找到用户。',

        // ── Extended Folio keys ──────────────────
        'Search by Folio ID...': '搜索账单编号...',
        'All Folios': '全部账单',
        'Open Folios': '未结账单',
        'Closed Folios': '已结账单',
        'Guest / Details': '宾客 / 详情',
        'Opened At': '开账时间',
        'Total Balance': '账单余额',
        'Pay': '付款',
        'Receipts': '收据',
        'Settle': '结算',
        'No active folios found.': '未找到活跃账单。',
        'Submit Charge': '提交费用',
        'Unit Price ($)': '单价 ($)',
        'Existing Methods': '现有支付方式',
        'Add New Method': '添加支付方式',
        'Method Name': '方式名称',
        'Add Method': '添加方式',
        'No payment methods defined yet.': '尚未定义支付方式。',
        'No receipts found for this folio.': '该账单暂无收据。',
        'Print Official Receipt': '打印正式收据',
        'Amount Paid:': '已付金额：',
        'Total Value': '总价值',

        // ── Extended Users keys ──────────────────
        'Add New User': '添加新用户',
        'User Profile': '用户档案',
        'System Role': '系统角色',
        'Contact Details': '联系方式',
        'Full Name': '全名',
        'Email Address': '电子邮箱',
        'Phone Number': '电话号码',
        'New Password (Optional)': '新密码（选填）',
        'Initial Password': '初始密码',
        'Account Active & Enabled': '账户激活且启用',
        'Provision User': '创建用户',
        'Update Profile': '更新档案',
        'Configure': '配置',
        'Retract Access': '撤销权限',
        'Authenticated': '已激活',
        'Disabled': '已停用',

        // ── Extended Employees keys ──────────────
        'Add Employee': '添加员工',
        'Manage Departments': '管理部门',
        'Register New Staff Member': '注册新员工',
        'Edit Employee Details': '编辑员工信息',
        'Designation': '职位',
        'Basic Salary ($)': '基本工资 ($)',
        'Date of Joining': '入职日期',
        'Languages Spoken': '语言能力',
        'ID Type': '证件类型',
        'Passport / ID Number': '护照 / 证件号码',
        'KRA PIN (Optional)': 'KRA税号（选填）',
        'Department Name': '部门名称',
        'Create Department': '创建部门',
        'No staff members found.': '未找到员工。',
        'Salary & Joining': '薪资与入职',
        'Identity': '身份证件',
        'Languages': '语言',

        // ── Extended Room Types keys ─────────────
        'Add Room Type': '添加房型',
        'Edit Room Type': '编辑房型',
        'Register New Type': '注册新类型',
        'Room Category Name': '房型名称',
        'Max Occupancy': '最大入住人数',
        'Bed Configuration': '床型配置',
        'Room Rate ($ per Night)': '房价（$/晚）',
        'Save Settings': '保存设置',
        'No room types defined yet.': '尚未定义房型。',
        'Setup': '配置',
        'Rate': '价格',

        // ── POS keys ────────────────────────────
        'All Items': '全部菜品',
        'Current Ticket': '当前订单',
        'Ticket is empty': '订单为空',
        'Immediate Payment (Direct)': '直接付款',
        'Charge to Room': '记入房账',
        'Direct Payment': '直接付款',
        'Room Tab': '挂账',
        'Guest Name (Optional)': '宾客姓名（选填）',
        'Post Charge to Folio': '记入账单',
        'Processing...': '处理中...',

        // ── Shared labels ────────────────────────
        'Adults': '成人',
        'Children': '儿童',
        'Not in the list?': '不在列表中？',
        'REGISTER NEW GUEST': '注册新宾客',
        'City or Country': '城市或国家',
        'Target Destination': '目标目的地',
        'Arriving From': '来自',
        'Next Destination': '下一目的地',
        'Arrival Flight #': '抵达航班号',
        'Departure Flight #': '离港航班号',
        'Stay Notes': '住宿备注',
        'Special requests, billing instructions, etc.': '特殊需求、结账说明等...',
        'Expected Checkout Date': '预计退房日期',
        'The total room charge will be calculated and posted to the folio automatically based on this date.': '系统将根据此日期自动计算并记录房费。',
        'Available Rooms': '可用房间',
        'No available rooms match this category.': '没有符合此类型的可用房间。',
        '-- Select Room Number --': '-- 选择房号 --',
        '-- Choose Room --': '-- 选择房间 --',
        'Record Arrival Payment': '记录到店付款',
        'Current Balance': '当前余额',
        'Overdue': '已逾期',
        'Due Today': '今日到期',
        'Print Report': '打印报告',
        'Download CSV': '下载CSV',
        'Management Reports': '管理报告',
        'Assign to Me': '分配给我',
        'Resolve': '解决',
        'Reported by': '上报人',
        'Issue Details': '问题详情',
        'Location / ID': '位置 / 编号',

        // Additional Reports & Finance Keys
        'Gross': '总额',
        'No guests found.': '未找到住客。',
        'Actual payments received': '实际收到款项',
        'Operational expenditures': '运营支出',
        'Accounts Payable': '应付账款',
        'Inventory Assets': '库存资产',
        '✓ Paid': '✓ 已付款',
        'Share (%)': '占比 (%)',
        'General Ledger': '总分类账',
        'Total Expenses': '总支出',
        'Running Balance': '运行余额',
        'All Maintenance Tickets': '所有维护工单',
        'available': '可用',
        'Guest Report': '住客报表',
        'Guests checking in today': '今日入住住客',
        'Collections - OpEx': '收款 - 运营支出',
        'Treasury Audit': '金库审计',
        'Repairs & Upkeep': '维修与保养',
        'All Reservations': '所有预订',
        'F&B / POS Report': '餐饮 / POS 报表',
        'Count': '数量',
        'All Registered Guests': '所有已登记住客',
        'Arrivals Today': '今日抵达',
        'New Arrivals Today': '今日新抵达',
        'Checked In': '已入住',
        'Date In': '入住日期',
        'Share': '占比',
        'Net Collections': '净收款额',
        'Payroll Liability': '工资负债',
        'Total Reservations': '总预订数',
        'Daily cash spend': '每日现金支出',
        'Revenue Report': '收入报表',
        'All Venue Bookings': '所有场馆预订',
        'Total Items': '总项目数',
        'Urgent / High': '紧急 / 高优先级',
        'Venue': '场馆',
        'Item Name': '项目名称',
        'Daily Cash Spend': '每日现金支出',
        'Client': '客户',
        'Debit / Credit': '借 / 贷',
        'Guests with Active Stays': '当前在住客',
        'Issue': '问题',
        'Inventory Report': '库存报表',
        'Venue Bookings Report': '场馆预订报表',
        'Active Collections': '活跃收款',
        'No venue bookings found.': '未找到场馆预订。',
        'Dining Orders': '餐饮订单',
        'Revenue by Charge Type': '按收费类型汇总的收入',
        'Supply Spend': '供应支出',
        'All Inventory Items': '所有库存项目',
        'Financial Reports': '财务报表',
        'No reservations found.': '未找到预订。',
        'Account': '账户',
        'By Department': '按部门',
        'Owed to Suppliers': '欠供应商款项',
        'No department data.': '无部门数据。',
        'Amount ($)': '金额 ($)',
        'Reservations Report': '预订报表',
        'Dining Sessions': '就餐场次',
        'Maintenance Report': '维护报表',
        'Guests checking out today': '今日退房住客',
        'Net Revenue': '净收入',
        'Open Sessions': '未结场次',
        'All-time Folio Value': '历史总账单价值',
        'Cash Collected': '收取的现金',
        'Out of Stock': '缺货',
        'Booked': '已预订',
        'Event': '活动',
        'Revenue audit and cash collection tracking': '收入审计和现金收款跟踪',
        'Total Employees': '员工总数',
        'Confirmed': '已确认',
        'Billed Revenue': '已结单收入',
        'Accounts Receivable': '应收账款',
        'Staff Salaries': '员工工资',
        'Debtor Tracking': '债务人跟踪',
        'Total invoices generated': '生成的发票总数',
        'Timestamp': '时间戳',
        'Session': '场次',
        'Total ($)': '总计 ($)',
        'No dining orders found.': '未找到餐饮订单。',
        'ID Number': '证件号码',
        'Employee Report': '员工报表',
        'Total Orders': '总订单数',
        'Deposit': '押金',
        'Well Stocked': '库存充足',
        'Stock Value': '库存价值',
        'Pending Folios': '待结账单',
        'occupied': '已占用',
        'Items with 0 quantity': '数量为 0 的项目',
        'Due from Guests': '应收住客款项',
        'No employees found.': '未找到员工。',
        'Stock Status': '库存状态',
        'Net Cash from Operations': '经营活动产生的净现金',
        'Departures Today': '今日离店',
        'Running Balance History': '运行余额历史记录',
        'Liquidity Summary': '流动性汇总',
        'Total POS Revenue': 'POS 总收入',
        'Items': '项目',
        'Procurement': '采购',
        'Total Guests': '总住客数',
        'Unrealized Revenue': '未实现收入',
        'No maintenance tickets found.': '未找到维护工单。',
        'Total Tickets': '总工单数',
        'Employee Directory': '员工目录',
        'Issue Card': '制卡',
        'Encode Guest Keycard': '宾客卡片编码',
        'Card Written Successfully!': '写入成功！',
        'Access for': '通行权限：',
        'is now active on Room': '已在房间激活：',
        'Encoding RFID Keycard...': 'RFID门卡编码中...',
        'Hold the proximity card against the USB encoder': '请将卡片贴近USB编码器',
        'Guest Full Name': '宾客全名',
        'Passport / ID Information': '护照 / 身份证信息',
        'Valid From': '有效起始',
        'Valid Until (Expiry)': '有效截止（过期）',
        'Encoding Process': '编码详情',
        'Place the physical card on the encoder and do not remove it until the process is complete.': '请将物理卡放在编码器上，直到过程完成前请勿移除。',
        'Burn Keycard': '写入卡片',

        'Register New Venue Booking': '登记新场地预订',
        'Edit Venue Booking': '编辑场地预订',
        'Venue / Client': '场地 / 客户',
        'Period / Timing': '时段 / 安排',
        'Guests & Financials': '人数与财务',
        'Select Venue': '选择场地',
        'Client Name': '客户姓名',
        'Client Phone': '客户电话',
        'Client Company': '客户公司',
        'Event Type': '活动类型',
        'Setup Type': '摆放形式',
        'Expected Guests': '预计人数',
        'Total Amount ($)': '总金额 ($)',
        'Deposit Paid': '定金已付',
        'Save Booking': '保存预订',
        'Create Booking': '创建预订',
        'CONFERENCE': '会议',
        'WEDDING': '婚礼',
        'BIRTHDAY': '生日',
        'GALA': '庆典',
        'SEMINAR': '研讨会',
        'WORKSHOP': '工作坊',
        'CORPORATE': '企业活动',
        'OTHER': '其他',
        'THEATER': '剧院式',
        'CLASSROOM': '教室式',
        'BOARDROOM': '董事会式',
        'BANQUET': '宴会式',
        'COCKTAIL': '酒会式',
        'U_SHAPE': 'U型',
        'HOLLOW_SQUARE': '中空方形',
        'OPEN': '开放式',
        'Manage Venues': '管理场地',

        'Financial & Operational Reports': '财务与运营报告',
        'Financial Performance Overview': '财务表现概览',
        'Total Collections': '总收款',
        'Net Cash Flow': '净现金流',
        'Pending from closed folios': '已结房账待收',
        'Unpaid purchase orders': '未付采购订单',
        'Supply Costs': '供应成本',
        'Procurement & Inventory': '采购与库存',
        'Revenue Distribution': '收入分布',
        'Details': '详情',
        'Financial Transaction Ledger': '财务交易台账',
        'No ledger entries for this period.': '此期间无台账记录。',
        'Operational Metrics Summary': '运营指标摘要',
        'No operational data for this period.': '此期间无运营数据。',
        'Revenue Contribution': '收入贡献',
        'Property Occupancy': '物业入住率',
        'Maintenance Overview': '维修概览',
        'Payroll Burden': '工资成本',
        'Treasury Management': '财务管理',
        'Manage and track venue bookings and event schedules.': '管理和跟踪场地预订及活动安排。',
        'Search client, venue...': '搜索客户、场地...',
        'Loading bookings...': '正在加载预订...',
        'to': '至',
        'Paid': '已付',
        'Unpaid': '未付',
        'Collections - Expenses': '收款 - 支出',

        'Total Records': '记录总数',
        'Past Stays': '历史住宿',
        'Upcoming': '即将到来',
        'Current State': '当前状态',
        'Idle': '空置',
        'Occupancy & Booking Calendar': '入住与预订日历',
        'Active Stay': '当前在住',
        'Active Checkout': '今日退房',
        'Financial reporting for this room is being compiled': '该房间的财务报表正在汇总中',
        'Total Room Revenue': '房费收入统计',
        'Maintenance & Housekeeping Logs': '维护与客房清洁日志',
        'No active maintenance tickets for this room': '该房间目前没有活跃的维护工单',
        'No history records found': '未找到历史记录',
        'Walk-in Guest': '散客',
        'Extend Guest Stay': '延长房客住宿',
        'New Departure Date': '新退房日期',
        'Modifying the departure date will update occupancy schedules for this room.': '修改退房日期将更新该房间的占用计划。',
        'Update Stay': '更新住宿',
        'Loading room details...': '正在加载房间详情...',
        'Stay': '入住',
        'Reserved': '已预订',

        'Asset & Liability Summary': '资产与负债摘要',
        'Capital Assets Purchased': '已购固定资产',
        'Maintenance Reserve': '维修储备金',
        'Petty Cash Balance': '备用金余额',
        'Total Payroll Obligations': '员工薪酬预提',
        'Date & Time': '日期与时间',
        'Account / Reference': '账户 / 参考',
        'Running Balance ($)': '运行余额 ($)',
        'Operational Statistics': '运营统计数据',
        'occupied Rooms': '已占用房间',
        'Expected Check-ins': '预计办理入住人数',
        'Expected Check-outs': '预计办理退房人数',
        'Recent Reservations': '近期预订',
        'total found': '条记录',
        'Balance': '余额',
    }
};

// ─── Context ───────────────────────────────────────────────────────────────
const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('hotel_crm_lang') || 'en';
    });

    const toggleLanguage = useCallback(() => {
        setLanguage(prev => {
            const next = prev === 'en' ? 'zh' : 'en';
            localStorage.setItem('hotel_crm_lang', next);
            return next;
        });
    }, []);

    const t = useCallback((key) => {
        return translations[language]?.[key] ?? key;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
    return ctx;
};

export default LanguageContext;
